FROM node:18-alpine

WORKDIR /app/frontend

# Install dependencies
COPY frontend/package*.json ./
RUN npm ci

# Copy source code
COPY frontend ./

# Expose port
EXPOSE 5173

# Start development server
CMD ["npm", "run", "dev"]